const Map<String, List<String>> keralaDistrictsAndCities = {
  'Alappuzha': ['Alappuzha', 'Chengannur', 'Kayamkulam', 'Mavelikkara', 'Cherthala', 'Other'],
  'Ernakulam': [
    'Kakkanad',
    'Kalamassery',
    'Edappally',
    'Kaloor',
    'Palarivattom',
    'Vyttila',
    'MG Road',
    'Thripunithura',
    'Kadavanthra',
    'Aluva',
    'Nettoor',
    'Panangad',
    'Vazhakkala',
    'Elamkulam',
    'Thevara',
    'Thammanam',
    'Kacherippady',
    'Perumbavoor',
    'Other'
  ],
  'Idukki': ['Thodupuzha', 'Munnar', 'Nedumkandam', 'Adimali', 'Kattappana', 'Other'],
  'Kannur': ['Kannur', 'Thalassery', 'Payyanur', 'Taliparamba', 'Iritty', 'Other'],
  'Kasaragod': ['Kasaragod', 'Kanhangad', 'Nileshwar', 'Uppala', 'Manjeshwar', 'Other'],
  'Kollam': ['Kollam', 'Karunagappalli', 'Punalur', 'Kottarakkara', 'Paravur', 'Other'],
  'Kottayam': ['Kottayam', 'Pala', 'Changanassery', 'Ettumanoor', 'Vaikom', 'Other'],
  'Kozhikode': ['Kozhikode', 'Vadakara', 'Koyilandy', 'Thamarassery', 'Feroke', 'Other'],
  'Malappuram': ['Malappuram', 'Manjeri', 'Tirur', 'Ponnani', 'Perinthalmanna', 'Other'],
  'Palakkad': ['Palakkad', 'Shoranur', 'Ottapalam', 'Mannarkkad', 'Chittur-Thathamangalam', 'Other'],
  'Pathanamthitta': ['Pathanamthitta', 'Thiruvalla', 'Adoor', 'Ranni', 'Kozhencherry', 'Other'],
  'Thiruvananthapuram': ['Thiruvananthapuram', 'Neyyattinkara', 'Attingal', 'Nedumangad', 'Varkala', 'Other'],
  'Thrissur': ['Thrissur', 'Chalakudy', 'Irinjalakuda', 'Kodungallur', 'Kunnamkulam', 'Other'],
  'Wayanad': ['Kalpetta', 'Mananthavady', 'Sulthan Bathery', 'Meenangadi', 'Panamaram', 'Other'],
};
